### ISSUE TITLE
Very poor performance on vot2019

### ISSUE THREAD

**Issue by makalo** [researchmm/Stark#5]
I am very interested in your work and thank you for your contribution. I tested Stark on vot19, and the configuration file used baseline_R101, but the result was very poor, with an EAO of 0.2. Is this result normal? Have you tested the result of vot2019?

**Comment by MasterBin-IIAU** [comment]
Hi, thanks for your interest in our work :)

Actually, we didn't test STARK on the VOT2019 because the previous failure-reset-based protocol is problematic. (More details about the comparison between the new protocol in VOT2020 and the old one in the previous VOT challenge in [VOT2020 paper](https://prints.vicos.si/publications/384/the-eighth-visual-object-tracking-vot2020-challenge-results))

When testing STARK on the VOT2020 benchmark, we found that STARK did struggle in dealing with distractors. It's not difficult to understand because STARK always assumes that there is only one target and only predicts one bounding box in each frame. Correspondingly, the previous failure-reset-based protocol "amplifies" the weakness of the trackers in dealing with distractors. To be specific, it may cause the tracker to fail many times in some sequences with distractors. I think that's why you get poor results on the VOT2019.

Thanks,
Bin
